-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Mutation exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias CreateTodoRequiredArguments =
    { data : Api.InputObject.TodoInput }


{-| Create a new document in the collection of 'Todo'

  - data - 'Todo' input values

-}
createTodo :
    CreateTodoRequiredArguments
    -> SelectionSet decodesTo Api.Object.Todo
    -> SelectionSet decodesTo RootMutation
createTodo requiredArgs____ object____ =
    Object.selectionForCompositeField "createTodo" [ Argument.required "data" requiredArgs____.data Api.InputObject.encodeTodoInput ] object____ Basics.identity


type alias UpdateTodoRequiredArguments =
    { id : Api.ScalarCodecs.Id
    , data : Api.InputObject.TodoInput
    }


{-| Update an existing document in the collection of 'Todo'

  - id - The 'Todo' document's ID
  - data - 'Todo' input values

-}
updateTodo :
    UpdateTodoRequiredArguments
    -> SelectionSet decodesTo Api.Object.Todo
    -> SelectionSet (Maybe decodesTo) RootMutation
updateTodo requiredArgs____ object____ =
    Object.selectionForCompositeField "updateTodo" [ Argument.required "id" requiredArgs____.id (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "data" requiredArgs____.data Api.InputObject.encodeTodoInput ] object____ (Basics.identity >> Decode.nullable)


type alias DeleteTodoRequiredArguments =
    { id : Api.ScalarCodecs.Id }


{-| Delete an existing document in the collection of 'Todo'

  - id - The 'Todo' document's ID

-}
deleteTodo :
    DeleteTodoRequiredArguments
    -> SelectionSet decodesTo Api.Object.Todo
    -> SelectionSet (Maybe decodesTo) RootMutation
deleteTodo requiredArgs____ object____ =
    Object.selectionForCompositeField "deleteTodo" [ Argument.required "id" requiredArgs____.id (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) ] object____ (Basics.identity >> Decode.nullable)


type alias PartialUpdateTodoRequiredArguments =
    { id : Api.ScalarCodecs.Id
    , data : Api.InputObject.PartialUpdateTodoInput
    }


{-| Partially updates an existing document in the collection of 'Todo'. It only
modifies the values that are specified in the arguments. During execution, it
verifies that required fields are not set to 'null'.

  - id - The 'Todo' document's ID
  - data - 'Todo' input values

-}
partialUpdateTodo :
    PartialUpdateTodoRequiredArguments
    -> SelectionSet decodesTo Api.Object.Todo
    -> SelectionSet (Maybe decodesTo) RootMutation
partialUpdateTodo requiredArgs____ object____ =
    Object.selectionForCompositeField "partialUpdateTodo" [ Argument.required "id" requiredArgs____.id (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "data" requiredArgs____.data Api.InputObject.encodePartialUpdateTodoInput ] object____ (Basics.identity >> Decode.nullable)
